### ISSUE TITLE
short PHP tag used in articles.php template results in parser error

### ISSUE THREAD

**Issue by peterblazejewicz** [niklausgerber/monochrome#1]
Short PHP tag used in one place in articles.php template file results in parser error on some installations with short tag support set off. That is probably small typo:
https://github.com/niklausgerber/monochrome/blob/master/site/templates/articles.php#L42

```
<? endif ?>
```

should be:

```
<?php endif ?>
```

thanks,
Peter

**Comment by niklausgerber** [comment]
Hi Peter

I missed that one. Thanks a lot for the change.

Cheers
Nik
